config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end 
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  validates :message, presence: true, length: {minimum: 3}
  validates :rating, presence: true

  RATINGS = {
    'One star': '1_star',
    'Two stars': '2_stars',
    'Three stars': '3_stars',
    'Four stars': '4_stars',
    'Five stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end 

  def send_comment_email
    NotificationsMailer.comment_added(self).deliver
  end 
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :place

  validates :picture, presence: true, length: {minimum: 3}
  validates :caption, length: {maximum: 100}
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  geocoded_by :address
  after_validation :geocode
  validates :name, presence: true, length: {minimum: 3}
  validates :address, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end 

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end 

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user:current_user))
    redirect_to place_path(@place)
  end 


  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end 

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @places = Place.paginate(:page => params[:page], :per_page => 10)
  end 

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end 
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end 

  def edit
    @place= Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end 
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

     <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Nomster", root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
             Add A Place
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>         
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1> Edit your place details </h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/places/index.html.erb
<!-- Bootstrap carousel start -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: "d-block img-fluid" %>
      <div class = "carousel-caption d-none d-md-block">
        Beaches of your dreams!
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', class: "d-block img-fluid" %>
      <div class = "carousel-caption d-none d-md-block">
        The best pizza places and restaurants!
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: "d-block img-fluid" %>
      <div class = "carousel-caption d-none d-md-block">
        Exciting modern art museums!
      </div>
    </div>
  </div>


  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- Bootstrap carousel end -->
<br />

<% @places.each do |place| %> 
  <div class="booyah-box col-10 offset-1 col-sm-8 offset-2">
    
    <h3><%= link_to place.name, place_path(place) %></h3>
    <i><%= place.address %></i><br /> <br />
    <p><%= place.description %></p><br />

    <% if place.photos.present? %> 
      <%= image_tag place.photos.last.picture, class: "img-homepage" %>    
      <br />               
    <% end %>

    <%if place.comments.present? %>
      <br />
      <div class="col-8">
          <blockquote>
            <% if place.comments.last.humanized_rating.present? %>
              <b><%= place.comments.last.humanized_rating %></b>
            <% end %>
            <br />
            <%= place.comments.last.message %>
            <br />
            <small><i> <%= place.comments.last.user.email %></i></small>
          </blockquote>
        </div>
      <% end %>

    <% if place.user.present? %>
      <small><i><%= place.user.email %></i></small>
    <% end %>
    <br />

    </div>

  <% end %>

</div> 

<br />

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, :container => false %>
</div>
<br />
<br />

app/views/places/new.html.erb
<div class="booyah-box col-8 offset-2">
  <br />
  <h2><center> Enter your place details </center></h2>
  <br />
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />    
    <%= f.submit 'Add', class: 'btn btn-primary' %>
  <br />
<% end %>

</div>

app/views/places/show.html.erb
<div class = "booyah-box col-10 offset-1">
  <h1> <strong> <%= @place.name %> </strong> </h1>
  <i> <%= @place.address %> </i> <br /> <br />
  <br />
  <p> <%= @place.description %> </p><br />

  <% if @place.latitude.present? && @place.longitude.present? %>


    <div id="map"></div>

    <script>
      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 13,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWojnSSJSn7XpDU16yq2tIyum58iXVFf4&callback=initMap">
    </script>

    <% end %>

    <br />
    <div class="float-right">
      <% if current_user && current_user== @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
        <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this entry?'}, class: 'btn btn-danger' %>  
      <% end %>
    </div>
    <br />  
  </div>


    <br class="clear" />

    <div class = "container col-10 offset-1">
      <div class = "photo-box">
        <h2> Photos </h2>
        <br />
         <div class = "row">
            <% if @place.photos.present? %>
              <% @place.photos.each do |photo| %>
                <div class = "col-12 col-sm-4">      
                <%= image_tag photo.picture, class: "img2" %>    
                <br />
                <%= photo.caption %>
                <br/>
                <small><i> <%= photo.user.email %></i></small>
                <br />
                <br />
                </div>
              <% end %>
            <% else %>
              <div class = "notice"> No photos have been uploaded yet. Be the first! </div>
              <br />
              <br />
            <% end %>
          </div>
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#PhotoModal">
          Add a Photo
          </button>
      </div>
    </div>

  <br class= "clear" />

  <!-- Modal -->
  <div class="modal fade" id="PhotoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="PhotoModalLabel">Add A Photo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
          <%= f.input :picture %>
          <%= f.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add Photo", class: 'btn btn-primary' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>


  <div class = "comment-box col-10 offset-1">
  
  <div class="clear"></div>
  
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="myModalLabel">Add A Comment</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="photo-box" >
    <h2> Comments </h2>
    <br />
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Add A Comment
    </button>
    <br/>
    <br />
    <br />
      <div class="row">
        <% if @place.comments.present? %>
          <% @place.comments.each do |comment| %>
            <div class="col-12">
              <blockquote>
                <% if comment.humanized_rating.present? %>
                  <b><%= comment.humanized_rating %></b>
                <% end %>
                <br />
                <%= comment.message %>
                <br />
                <small><i> <%= comment.user.email %></i></small>
                <br />
              </blockquote>
            </div>
          <% end %>
        <% else %>
          <div class = "notice"> No comments have been added yet. Be the first! </div>
          <br />
          <br />
        <% end %>
  </div>

</div>

app/views/users/show.html.erb
 <div class="booyah-box col-10 offset-1">

  <div class ="row">
    <div class = "col-4">
      <%= image_tag 'user.png', class: "profile-photo" %>
    </div>

    <div class= "col-8"
      <h1><%= @user.email %></h1>
      <br />
      <h3> Member Since: <%= @user.created_at.strftime("%B %d, %Y") %> </h3>
      <br />
      <h4><i><%= @user.comments.count %> total comments </i></h4>
      <h4><i><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews </i></h4>
    </div>
  </div class="clear"></div>
</div>

<br />


<div class="booyah-box col-10 offset-1">
  <h3 class="text-center">Your Places</h3>
  <br/>
  <% if @user.places.present? %>
    <% @user.places.each do |place| %> 
      <%= link_to place.name, place_path(place) %>
      <i><small><%= place.address %></small></i>
      <p><small><%= place.description %></small></p><br />
    <% end %>
  <% else %>
    <h6> You haven't made any places yet! <%= link_to 'Add A Place Now!', new_place_path %> </h6>
    <br />
  <% end %>
</div class="clear"></div>

<br />


<div class="booyah-box col-10 offset-1">
  <h3 class="text-center"> Your Comments </h3>
  <% if @user.comments.present? %>
    <div class = "row">
      <% @user.comments.each do |comment| %>
        <div class="col-12 col-sm-6">
          <blockquote>
            <% if comment.humanized_rating.present? %>
              <b><%= comment.humanized_rating %></b> -
            <% end %>
            <strong> <%= link_to comment.place.name, place_path(comment.place) %> </strong>
            <br />
            <%= comment.message %>
          </blockquote>
        </div>
      <% end %>
    </div>
  <% else %>
    <br/>
    <h6> You haven't made any comments yet! </h6>
    <br />
  <% end %>

</div>